export type ColorSwatch = {
  name: string;
  hex: string;
  slug: string;
  variable: string;
};

export const colorSwatches: ColorSwatch[] = [
  { name: "Isabelline", hex: "#EEE8E3", slug: "isabelline", variable: "--isabelline" },
  {
    name: "Rose Text Secondary",
    hex: "#FF6868",
    slug: "rose-text-secondary",
    variable: "--rose-text-secondary",
  },
  { name: "White", hex: "#FFFFFF", slug: "white", variable: "--white" },
  { name: "Light Pink", hex: "#FF7777", slug: "light-pink", variable: "--light-pink" },
  {
    name: "Yellow Text Tertiary",
    hex: "#DFFF03",
    slug: "yellow-text-tertiary",
    variable: "--yellow-text-tertiary",
  },
  { name: "Transparent", hex: "#FFF0", slug: "transparent", variable: "--transparent" },
  {
    name: "Gray Text Alternate",
    hex: "#4C475A",
    slug: "gray-text-alternate",
    variable: "--gray-text-alternate",
  },
  {
    name: "Brown BG Primary",
    hex: "#939174",
    slug: "brown-bg-primary",
    variable: "--brown-bg-primary",
  },
  {
    name: "Sky Blue BG Secondary",
    hex: "#24EFD7",
    slug: "sky-blue-bg-secondary",
    variable: "--sky-blue-bg-secondary",
  },
  {
    name: "Pink BG Tertiary",
    hex: "#FFB2EE",
    slug: "pink-bg-tertiary",
    variable: "--pink-bg-tertiary",
  },
  { name: "Aquamarine", hex: "#10FFB5", slug: "aquamarine", variable: "--aquamarine" },
  { name: "Gunmetal (CTA)", hex: "#1B2E36", slug: "gunmetal", variable: "--gunmetal" },
  { name: "Light Red", hex: "#D95959", slug: "light-red", variable: "--light-red" },
  { name: "Rose 2", hex: "#FC6C74", slug: "rose-2", variable: "--rose-2" },
  { name: "Mid Gray", hex: "#737373", slug: "mid-gray", variable: "--mid-gray" },
  { name: "Lightest Blue", hex: "#C7DFDE", slug: "lightest-blue", variable: "--lightest-blue" },
  { name: "House Red", hex: "#D4001E", slug: "house-red", variable: "--house-red" },
  { name: "House White", hex: "#F8F8F8", slug: "house-white", variable: "--house-white" },
  { name: "House Green", hex: "#616718", slug: "house-green", variable: "--house-green" },
  { name: "House Blue", hex: "#515DD3", slug: "house-blue", variable: "--house-blue" },
  { name: "House Yellow", hex: "#FCEF22", slug: "house-yellow", variable: "--house-yellow" },
  {
    name: "Mid Night Blue",
    hex: "#282B3C",
    slug: "mid-night-blue",
    variable: "--mid-night-blue",
  },
  { name: "Blue Crayola", hex: "#4D77FF", slug: "blue-crayola", variable: "--blue-crayola" },
  { name: "Alabaster", hex: "#EEEBE2", slug: "alabaster", variable: "--alabaster" },
  {
    name: "African Violet",
    hex: "#CB8DBE",
    slug: "african-violet",
    variable: "--african-violet",
  },
  { name: "Sunset", hex: "#F9C57D", slug: "sunset", variable: "--sunset" },
  { name: "Space Cadet", hex: "#252657", slug: "space-cadet", variable: "--space-cadet" },
  {
    name: "Post-It Yellow",
    hex: "#FFFA95",
    slug: "post-it-yellow",
    variable: "--post-it-yellow",
  },
  { name: "Black 35", hex: "#00000059", slug: "black-35", variable: "--black-35" },
  { name: "Rich Black 5", hex: "#0E191D", slug: "rich-black-5", variable: "--rich-black-5" },
  {
    name: "Aquamarine Hover",
    hex: "#0DE6A3",
    slug: "aquamarine-hover",
    variable: "--aquamarine-hover",
  },
  {
    name: "Aquamarine Light",
    hex: "#8AFFDA",
    slug: "aquamarine-light",
    variable: "--aquamarine-light",
  },
  { name: "Rich Black", hex: "#030506", slug: "rich-black", variable: "--rich-black" },
  { name: "Night", hex: "#090E10", slug: "night", variable: "--night" },
  {
    name: "Rich Green Black",
    hex: "#0F1A1E",
    slug: "rich-green-black",
    variable: "--rich-green-black",
  },
  { name: "Green Apple", hex: "#B0B839", slug: "green-apple", variable: "--green-apple" },
  { name: "Rich Black 2", hex: "#0E191D", slug: "rich-black-2", variable: "--rich-black-2" },
  { name: "Footer Black", hex: "#0E181C", slug: "footer-black", variable: "--footer-black" },
  { name: "Tiga Red", hex: "#CF0B05", slug: "tiga-red", variable: "--tiga-red" },
  { name: "Sera Blue", hex: "#515DD3", slug: "sera-blue", variable: "--sera-blue" },
  { name: "Orli White", hex: "#C7DFDE", slug: "orli-white", variable: "--orli-white" },
  {
    name: "Orli White Dark",
    hex: "#82B5B3",
    slug: "orli-white-dark",
    variable: "--orli-white-dark",
  },
  { name: "Pan Yellow", hex: "#FCEF22", slug: "pan-yellow", variable: "--pan-yellow" },
  {
    name: "Pan Yellow Dark",
    hex: "#FFA928",
    slug: "pan-yellow-dark",
    variable: "--pan-yellow-dark",
  },
  {
    name: "Rich Text Black",
    hex: "#0C1418",
    slug: "rich-text-black",
    variable: "--rich-text-black",
  },
  {
    name: "Rich Black Text",
    hex: "#0C1418",
    slug: "rich-black-text",
    variable: "--rich-black-text",
  },
  { name: "Black 2", hex: "#020404", slug: "black-2", variable: "--black-2" },
  { name: "Purple", hex: "#A537E5", slug: "purple", variable: "--purple" },
  { name: "Off White", hex: "#F6F1EC", slug: "off-white", variable: "--off-white" },
  {
    name: "Referral Black",
    hex: "#161616",
    slug: "referral-black",
    variable: "--referral-black",
  },
  { name: "Rich Black 3", hex: "#0F1A1E", slug: "rich-black-3", variable: "--rich-black-3" },
  { name: "DiveIn Bubble", hex: "#2D2E40", slug: "divein-bubble", variable: "--divein-bubble" },
  { name: "Mount Pink", hex: "#A47086", slug: "mount-pink", variable: "--mount-pink" },
  { name: "Savoy", hex: "#6064D9", slug: "savoy", variable: "--savoy" },
  { name: "Delft", hex: "#303171", slug: "delft", variable: "--delft" },
  { name: "Ivory", hex: "#FFFDEC", slug: "ivory", variable: "--ivory" },
  { name: "Dark Purple", hex: "#191025", slug: "dark-purple", variable: "--dark-purple" },
  { name: "Citrine", hex: "#CECD23", slug: "citrine", variable: "--citrine" },
  { name: "Gunmetal 2", hex: "#15252C", slug: "gunmetal-2", variable: "--gunmetal-2" },
  {
    name: "Arylide Yellow",
    hex: "#E7CA63",
    slug: "arylide-yellow",
    variable: "--arylide-yellow",
  },
  { name: "Icterine", hex: "#F6F33D", slug: "icterine", variable: "--icterine" },
  { name: "Neon Blue", hex: "#4E62EE", slug: "neon-blue", variable: "--neon-blue" },
  {
    name: "Raisin Black 3",
    hex: "#222335",
    slug: "raisin-black-3",
    variable: "--raisin-black-3",
  },
  {
    name: "Raisin Black 2",
    hex: "#1B1B28",
    slug: "raisin-black-2",
    variable: "--raisin-black-2",
  },
  {
    name: "Space Cadet 2",
    hex: "#2C2C42",
    slug: "space-cadet-2",
    variable: "--space-cadet-2",
  },
  { name: "Lapis Lazuli", hex: "#42669B", slug: "lapis-lazuli", variable: "--lapis-lazuli" },
  {
    name: "Palatine Blue",
    hex: "#4032DB",
    slug: "palatine-blue",
    variable: "--palatine-blue",
  },
  { name: "Marian Blue", hex: "#454B8D", slug: "marian-blue", variable: "--marian-blue" },
  { name: "Satin", hex: "#EDEAE0", slug: "satin", variable: "--satin" },
  { name: "Cloud Brust", hex: "#1E314C", slug: "cloud-brust", variable: "--cloud-brust" },
  { name: "Blueberry", hex: "#4B76FF", slug: "blueberry", variable: "--blueberry" },
  { name: "Light Black", hex: "#080808", slug: "light-black", variable: "--light-black" },
  { name: "Footer Dark", hex: "#222222", slug: "footer-dark", variable: "--footer-dark" },
  {
    name: "Sera Blue Dark",
    hex: "#3C47B6",
    slug: "sera-blue-dark",
    variable: "--sera-blue-dark",
  },
  {
    name: "Garu Green Dark",
    hex: "#979E28",
    slug: "garu-green-dark",
    variable: "--garu-green-dark",
  },
  {
    name: "Tiga Red Dark",
    hex: "#AA130E",
    slug: "tiga-red-dark",
    variable: "--tiga-red-dark",
  },
  {
    name: "Darkest Green",
    hex: "#0F1A1E",
    slug: "darkest-green",
    variable: "--darkest-green",
  },
  { name: "Rich Black 4", hex: "#10181C", slug: "rich-black-4", variable: "--rich-black-4" },
  { name: "Eggshell", hex: "#E9E7D4", slug: "eggshell", variable: "--eggshell" },
  { name: "Shady", hex: "#9C9A9C", slug: "shady", variable: "--shady" },
  { name: "Rose 1", hex: "#FC6D75", slug: "rose-1", variable: "--rose-1" },
];
